version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jdungeon-common-server
    container_name: jdungeon-common-server
    restart: always
    environment:
      - NODE_ENV=production
    network_mode: "host"
